# Generated by Django 5.2.3 on 2025-06-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('claim_number', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('lpo_confirmed', models.BooleanField(default=False)),
                ('estimated_time_cost', models.CharField(choices=[('nodamage', 'No Damage'), ('cheap', 'Cheap'), ('lite', 'Lite'), ('mid', 'Mid'), ('heavy', 'Heavy')], default='mid', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending_expert', 'Pending for Expert'), ('pending_approval', 'Pending Approval'), ('pending_start', 'Pending to Start'), ('pending_part', 'Pending Part'), ('working', 'Working'), ('ready_exit', 'Ready for Exit'), ('archived', 'Archived')], max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_parts', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.car')),
            ],
        ),
    ]
