# Generated by Django 5.2.3 on 2025-07-11 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='claim_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='estimated_time_cost',
        ),
        migrations.RemoveField(
            model_name='car',
            name='lpo_confirmed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='registered_at',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Plate Number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='RepairJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_expert', 'Pending for Expert'), ('pending_approval', 'Pending Approval'), ('pending_start', 'Pending to Start'), ('pending_part', 'Pending Part'), ('working', 'Working'), ('ready_exit', 'Ready for Exit'), ('archived', 'Archived')], default='pending_expert', max_length=20, verbose_name='Status')),
                ('claim_number', models.CharField(max_length=50, verbose_name='Claim Number')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered At')),
                ('estimated_time_cost', models.CharField(choices=[('nodamage', 'No Damage'), ('cheap', 'Cheap'), ('lite', 'Lite'), ('mid', 'Mid'), ('heavy', 'Heavy')], default='mid', max_length=10, verbose_name='Estimated Cost Level')),
                ('deal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deal Amount')),
                ('lpo_confirmed', models.BooleanField(default=False, verbose_name='LPO Confirmed')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Repair Job',
                'verbose_name_plural': 'Repair Jobs',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('picture', models.ImageField(upload_to='parts/', verbose_name='Part Picture')),
                ('repair_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.repairjob', verbose_name='Repair Job')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.DeleteModel(
            name='CarStage',
        ),
    ]
