# Generated by Django 5.2.3 on 2025-08-03 13:00

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='picture',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='position',
            field=models.CharField(choices=[('front_left', 'Front Left'), ('front_right', 'Front Right'), ('rear_left', 'Rear Left'), ('rear_right', 'Rear Right'), ('center', 'Center'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='name',
            field=markdownx.models.MarkdownxField(verbose_name='Item Name / Description'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
    ]
