# Generated by Django 5.2.3 on 2025-08-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_quotationitem_picture_quotationitem_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='name',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Custom Item Name (if not in list)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itemname', verbose_name='Item Name'),
        ),
    ]
