# Generated by Django 5.2.3 on 2025-07-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_car_options_alter_repairjob_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='estimate_number',
        ),
    ]
