# Generated by Django 5.2.3 on 2025-08-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_repairjob_options_alter_quotationitem_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='vin_number',
        ),
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='VIN Number'),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='Unnamed Owner', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='core.owner'),
        ),
        migrations.AlterField(
            model_name='repairjob',
            name='status',
            field=models.CharField(choices=[('pending_expert', 'Pending for Expert'), ('quotation', 'Quotation'), ('pending_approval', 'Pending Approval'), ('pending_start', 'Pending to Start'), ('pending_part', 'Pending Part'), ('working', 'Working'), ('ready_exit', 'Ready To Exit'), ('sign', 'Waiting For Sign'), ('exit', 'Exit (Awaiting LPO)'), ('paid', 'Waiting For Pay'), ('archived', 'Archived')], default='pending_expert', max_length=20, verbose_name='Status'),
        ),
    ]
