# Generated by Django 5.2.3 on 2025-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_owner_first_name_remove_owner_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('MERCEDES', 'MERCEDES'), ('BMW', 'BMW'), ('GMC', 'GMC'), ('NISSAN', 'NISSAN'), ('HYUNDAI', 'HYUNDAI'), ('AUDI', 'AUDI'), ('TOYOTA', 'TOYOTA'), ('LEXUS', 'LEXUS'), ('INFINITY', 'INFINITY'), ('DODGE', 'DODGE'), ('MAZDA', 'MAZDA'), ('HONDA', 'HONDA'), ('KIA', 'KIA'), ('LAND ROVER', 'LAND ROVER'), ('PORSCHE', 'PORSCHE'), ('CHEVROLET', 'CHEVROLET'), ('FORD', 'FORD'), ('PEUGEOT', 'Peugeot'), ('JEEP', 'JEEP'), ('MITSUBISHI', 'MITSUBISHI'), ('SUZUKI', 'SUZUKI'), ('V WAGON', 'V WAGON'), ('MINI', 'MINI'), ('MG', 'MG'), ('RENAULT', 'RENUALT'), ('GENESIS', 'GENESIS'), ('CHANGAN', 'CHANGAN'), ('GEELY', 'GEELY'), ('SUBARU', 'SUBARU'), ('CADILLAC', 'CADILAC'), ('JETOUR', 'JETOUR'), ('JAGUAR', 'JAGUAR'), ('VOLVO', 'VOLVO'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('WHITE', 'White'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('SILVER', 'Silver'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('GRAY', 'Gray'), ('GOLD', 'Gold'), ('BROWN', 'Brown')], default='WHITE', max_length=20, verbose_name='Color'),
        ),
    ]
