# Generated by Django 5.2.3 on 2025-07-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_repairjob_timer_end_time_repairjob_timer_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.FloatField(default=10.0, max_length=50, verbose_name='PartPrice'),
        ),
    ]
