# Generated by Django 5.2.3 on 2025-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_car_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='Is Bought?'),
        ),
    ]
