# Generated by Django 5.2.3 on 2025-07-17 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('garage', 'Garage Expense'), ('personal', 'Personal Expense')], max_length=10, verbose_name='Type of Expense')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('transaction_date', models.DateTimeField(verbose_name='Date and Time of Transaction')),
                ('custom_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Category (Other)')),
                ('person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Person's Name")),
                ('personal_type', models.CharField(blank=True, choices=[('advance', 'Advance (Employee Debt)'), ('reimbursement', 'Reimbursement (Employee Credit)')], max_length=15, null=True, verbose_name='Type of Personal Transaction')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.expensecategory', verbose_name='Expense Category')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source of Income (Payer)')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('transaction_date', models.DateTimeField(verbose_name='Date and Time of Transaction')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('repair_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repairjob', verbose_name='Related Repair Job')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
