# Generated by Django 4.2.5 on 2025-08-05 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_car_brand_alter_car_color'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(default='-', max_length=20, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_card',
            field=models.CharField(default='-', max_length=20, verbose_name='ID Card'),
        ),
        migrations.AddField(
            model_name='expense',
            name='related_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.part', verbose_name='Related Part (if any)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('garage', 'Garage Expense'), ('personal', 'Personal Expense'), ('part', 'Car Part'), ('other', 'Other')], max_length=10, verbose_name='Type of Expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
    ]
