# Generated by Django 4.2.5 on 2025-08-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_repairjob_is_archived_alter_repairjob_car'),
        ('accounting', '0002_remove_expensecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-transaction_date'], 'permissions': [('can_change_expense_recorder', 'Can change the recorder of an expense')]},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='custom_category',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('garage', 'Garage Funds'), ('personal', 'Personal Pocket')], default='garage', max_length=10, verbose_name='Payment Source'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('garage', 'Garage Expense'), ('personal', 'Personal Expense'), ('part', 'Part Purchase'), ('other', 'Other')], max_length=10, verbose_name='Type of Expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='related_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.part', verbose_name='Related Part'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source of Income (Payer)'),
        ),
        migrations.AlterField(
            model_name='income',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Transaction'),
        ),
    ]
