# Generated by Django 5.2.3 on 2025-07-27 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_employee_salaryslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Absence')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason for Absence')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='accounting.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
