# Generated by Django 5.2.3 on 2025-07-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='person_name',
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.employee', verbose_name='Employee'),
        ),
    ]
