# Generated by Django 4.2.5 on 2025-08-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_expense_options_remove_expense_custom_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Period Closed?'),
        ),
    ]
